### ISSUE TITLE
coffeescript line numbers latest zappajs (using teacup)

### ISSUE THREAD

**Issue by Karl01** [zappajs/zappajs#129]
Hi,
using the modified example code I get the wrong line numbers:

    # This is the example from README.md
    # 6-2-18 testing
    zappa = require('zappajs')
    fs = require('fs')    
    ## HTTPS ##
    https_options =
      key: fs.readFileSync '/home/xxxxxxx/proj42/cert/privkey.pem' # root!
      cert: fs.readFileSync '/home/xxxxxxx/proj42/cert/fullchain.pem'

    zappa.run 3444, process.env.HOST_IP,disable_io:true,https:https_options, ->

      ## Server-side ##
      teacup = @teacup

      @get '/': ->
        console.log "boom = ",boom     # = line 18
        @render 'index',
          title: 'Zappa!'
          scripts: '/index.js /more.js /client.js'
          stylesheet: '/index.css'

      @view index: ->
        {doctype,html,head,title,script,link,body,h1,div} = teacup
        doctype 5
        html =>
          head =>
            title @title if @title
            for s in @scripts.split ' '
              script src: s
            link rel:'stylesheet', href:@stylesheet
          body ->
            h1 'Welcome to Zappa!'
            div id:'content'
            div id:'content2'
    
      pixels = 12

      @css '/index.css':
        body:
          font: '30px Helvetica'
        h1:
          color: 'pink'
          height: "#{pixels}px"

  
etc

Error shows line 18 as line 27

    [nodemon] starting `coffee --nodejs --stack_size=10240 readme.coffee` 
    ReferenceError: boom is not defined
        at Object./ (/home/xxxxxxx/proj42/readme.coffee:27:32)
        at seemify (/home/xxxxxxx/proj42/node_modules/zappajs/lib/seemify.js:19:13)
        at /home/xxxxxxx/proj42/node_modules/zappajs/lib/route.js:145:20
        at Layer.handle [as handle_request] 
    ...

**Comment by shimaore** [comment]
What you are seeing is most probably the JavaScript line number (if you try to compile the module with `coffee -c` the error should be on line 27 of the `.js`). I haven't seen this kind of issues in a while in coffeescript, but I also tend to pre-compile to `.js` nowadays :)

There [used to be](https://github.com/mochajs/mocha/issues/651) a similar issue with mocha, any chance this could be related to using `nodemon`? (e.g. does `coffee --nodejs --stack_size=10240 readme.coffee` at the command-line have the same trouble?)

**Comment by Karl01** [comment]
ETU1$ coffee --nodejs --stack_size=10240 readme.coffee
    ReferenceError: boom is not defined
        at Object./ (/home/xxxxxx/proj42/readme.coffee:27:32)
        at seemify (/home/xxxxxx/proj42/node_modules/zappajs/lib/seemify.js:19:13)

Thanks, it's not nodemon but I can live with the .js debugging method. Without Zappa/teacup it maps correctly. Teacup issue? I seem to remember a coffecup issue with line maps from way back

    ETU1$ coffee --nodejs --stack_size=10240 readme.coffee
    ReferenceError: boom is not defined
    at Object.<anonymous> (/home/xxxxxxx/proj42/readme.coffee:12:23)
    at Object.<anonymous> (/home/xxxxxxx/proj42/readme.coffee:1:1)
    at Module._compile (module.js:570:32)

    ETU1$ nodemon --delay 5 --exec coffee --nodejs --stack_size=10240 readme.coffee  [nodemon]1.14.12
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: *.*
    [nodemon] starting `coffee --nodejs --stack_size=10240 readme.coffee`
    ReferenceError: boom is not defined
        at Object.<anonymous> (/home/userpt18z97/proj42/readme.coffee:12:23)

    1 # This is the example from README.md
    2 # 6-2-18 testing
    3 #zappa = require('zappajs')
    4 fs = require('fs')
    5 ## HTTPS ##
    6 https_options =
    7   # chown root.root privkey.pem, fullchain also works root owned
    8   #for more options see http://nodejs.org/api/https.html
    9   key: fs.readFileSync '/home/xxxxxxxx/proj42/cert/privkey.pem' # root!
    10   cert: fs.readFileSync '/home/xxxxxxx/proj42/cert/fullchain.pem'
    11
    12 console.log "boom = ",boom   # error shows line 18 as line 27
    13
    14 #zappa.run 3444, process.env.HOST_IP,disable_io:true,https:https_options, ->
    15 #
    16 #  ## Server-side ##
    17 #  teacup = @teacup
    18 #
    19 #  @get '/': ->
