### ISSUE TITLE
Error: Cannot find module 'zappajs' 0.4.3

### ISSUE THREAD

**Issue by ghost** [zappajs/zappajs#30]
I can't run coffee hi.coffee

Error: Cannot find module 'zappajs' 
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/Users/ap/hi.coffee:3:3) 
    at Object.<anonymous> (/Users/ap/hi.coffee:9:4)
    at Module._compile (module.js:446:26) 
    at Object.run (/usr/lib/nodejs/coffee-script/lib/coffee-script/coffee-script.js:68:25)
    at /usr/lib/nodejs/coffee-script/lib/coffee-script/command.js:135:29
    at /usr/lib/nodejs/coffee-script/lib/coffee-script/command.js:110:18

**Comment by shimaore** [comment]
Please try again with `zappajs@0.4.4`.

**Comment by ghost** [comment]
Yes, 0.4.4 is work.

**Comment by shimaore** [comment]
Also: 0.4.5 fixes the issue you mentioned in private email regarding socket.io.js not starting.

**Comment by scien** [comment]
confirmed 0.4.5 fixed the issue with not being able to load /socket.io/socket.io.js
